In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

In [19]:
m = nn.Conv1d(16, 16, 3)
input = torch.randn(20, 16, 50)

In [20]:
output = m(input)

In [21]:
output.shape

torch.Size([20, 16, 48])

In [15]:
# 20 x (16 x 50) -> 20 x (33 x 48)

In [41]:
# 128 x (3 x 128) -> 128 x (3 x 64)

In [46]:
m = nn.Conv1d(3, 3, 65)
input = torch.randn(128, 3, 128)

In [47]:
m(input).shape

torch.Size([128, 3, 64])

In [48]:
input[0][0]

tensor([ 0.4311,  0.4223, -0.1012,  0.4079, -1.4033, -0.3094, -0.7310, -0.5546,
         1.2743,  0.3508, -0.7578,  0.1833,  1.4225,  0.3390, -0.5225, -1.0757,
        -0.4338,  1.9633,  1.5587, -0.9259,  0.4802,  1.4960, -1.3043, -0.1574,
         2.5176, -0.8280, -1.3436, -0.0147,  0.9149, -0.5770,  0.7857,  0.5865,
        -0.7292,  0.6710, -0.7322,  0.7331,  0.7834,  0.9382, -1.3191, -0.7954,
        -0.2505, -0.1937,  0.1589, -0.4286,  1.7501,  1.4324,  0.2227,  0.0440,
        -0.7726, -0.9869,  0.9172,  0.2647,  0.5396,  0.3858,  0.3276,  0.6935,
         0.1652, -0.6218, -2.1617, -0.6580,  0.5294,  0.5957,  1.2561,  0.5966,
         0.9625, -0.9995, -1.3388, -0.1939, -1.0310, -0.3308, -0.1624,  0.4423,
         1.0738, -1.7962, -0.9491,  0.0120, -0.1206,  1.6342,  1.1364,  0.3616,
        -1.2972, -1.0015, -2.0912,  0.7317, -0.3493, -1.2688, -0.1780,  0.8421,
         0.2467, -1.6183,  0.0893,  0.3663,  1.4880,  0.3169, -0.8347,  2.1452,
         0.6265,  0.7724,  0.8620,  0.33

In [68]:
m = nn.Conv1d(3, 3, 3)
input = torch.randn(1, 3, 5)

In [69]:
m(input)

tensor([[[-0.1417, -1.0276,  0.0777],
         [-0.8669,  1.1465, -0.6918],
         [ 0.1080, -0.2748, -0.3590]]], grad_fn=<SqueezeBackward1>)

In [70]:
input

tensor([[[ 0.9216,  0.1795,  1.0452,  1.6897,  0.6351],
         [-1.5135, -1.5387, -0.5990, -1.3724,  0.2759],
         [ 1.2232, -1.3808,  1.6702, -0.7384,  0.9874]]])

In [75]:
m.weight, m.bias

(Parameter containing:
 tensor([[[ 0.2947, -0.2861, -0.1842],
          [ 0.1423, -0.2574,  0.1383],
          [ 0.3067,  0.2115, -0.0851]],
 
         [[-0.0919,  0.0674,  0.0819],
          [-0.1968,  0.2449,  0.0792],
          [-0.1944,  0.2336, -0.1833]],
 
         [[ 0.0758, -0.2465, -0.1027],
          [-0.0121, -0.2828, -0.1304],
          [-0.0341, -0.1480, -0.1995]]], requires_grad=True),
 Parameter containing:
 tensor([-0.2081,  0.1130, -0.1712], requires_grad=True))

In [79]:
sum(m.weight[0][0] * input[0][0][:-2]) + m.bias[0]

tensor(-0.1804, grad_fn=<AddBackward0>)